# travis-ci.org

language: node_js
node_js:
  - "lts/*"

sudo: false

cache:
  directories:
    - "node_modules"

before_install:
  - npm install --global npm@"^5.4.0"

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: never
    on_failure: change
